"""
MedGemma FastAPI Application - Main Entry Point.

This module defines all API endpoints for the MedGemma medical AI service.
Designed for deployment on RunPod with A6000 GPU (48GB VRAM).

Endpoints:
- GET  /health              - Health check and model status
- POST /v1/chat/completions - OpenAI-compatible chat API
- POST /v1/medical/query    - Text-only medical queries
- POST /v1/medical/analyze  - Medical image analysis
- POST /v1/medical/report   - Medical report generation

Source: FastAPI documentation
URL: https://fastapi.tiangolo.com/
Verified: 2025-12-06
"""

import logging
import uuid
from contextlib import asynccontextmanager
from datetime import datetime

from fastapi import Depends, FastAPI, HTTPException, status
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import JSONResponse

from src.auth import APIKeyDep
from src.config import Settings, get_settings
from src.models.requests import (
    ChatCompletionRequest,
    ImageAnalysisRequest,
    MedicalQueryRequest,
    MedicalReportRequest,
)
from src.models.responses import (
    ChatCompletionResponse,
    Choice,
    ErrorResponse,
    HealthResponse,
    ImageAnalysisResponse,
    MedicalQueryResponse,
    MedicalReportResponse,
    UsageInfo,
    GPUInfo,
    PerformanceInfo,
)
from src.services.medgemma import MedGemmaService, get_medgemma_service

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s - %(name)s - %(levelname)s - %(message)s",
)
logger = logging.getLogger(__name__)


@asynccontextmanager
async def lifespan(app: FastAPI):
    """
    Application lifespan manager.

    Handles model loading on startup and cleanup on shutdown.
    Model is loaded once and cached for all requests.
    """
    logger.info("Starting MedGemma API...")

    # Load model on startup
    service = get_medgemma_service()
    try:
        service.load_model()
        logger.info("Model loaded successfully, API is ready!")
    except Exception as e:
        logger.error(f"Failed to load model: {e}")
        # Don't raise - allow health endpoint to report error status
        logger.warning("API starting without model - check /health for status")

    yield

    # Cleanup on shutdown
    logger.info("Shutting down MedGemma API...")


# Initialize FastAPI app
settings = get_settings()
app = FastAPI(
    title=settings.api_title,
    description=settings.api_description,
    version=settings.api_version,
    lifespan=lifespan,
    docs_url="/docs",
    redoc_url="/redoc",
    openapi_url="/openapi.json",
)

# Add CORS middleware for web clients
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],  # Configure appropriately for production
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


# Medical disclaimer constant
MEDICAL_DISCLAIMER = """
**DISCLAIMER**: This response is generated by an AI model and is for informational
purposes only. It should not be used as a substitute for professional medical advice,
diagnosis, or treatment. Always seek the advice of a qualified healthcare provider
with any questions you may have regarding a medical condition.
"""


# =============================================================================
# Health Check Endpoint (No Auth Required)
# =============================================================================


@app.get(
    "/health",
    response_model=HealthResponse,
    tags=["Health"],
    summary="Health check endpoint",
    description="Returns service health status and model information. No authentication required.",
)
async def health_check() -> HealthResponse:
    """
    Check service health and model status.

    Returns GPU memory usage and model loading status.
    Useful for RunPod health checks and monitoring.
    """
    service = get_medgemma_service()
    health_data = service.health_check()

    # Build performance info if available
    perf_info = None
    if "performance" in health_data:
        perf_info = PerformanceInfo(**health_data["performance"])

    return HealthResponse(
        status=health_data["status"],
        model_loaded=health_data["model_loaded"],
        model_id=health_data["model_id"],
        quantization=health_data["quantization"],
        gpu=GPUInfo(**health_data["gpu"]),
        performance=perf_info,
        version=settings.api_version,
    )


# =============================================================================
# OpenAI-Compatible Chat Endpoint
# =============================================================================


@app.post(
    "/v1/chat/completions",
    response_model=ChatCompletionResponse,
    tags=["Chat"],
    summary="OpenAI-compatible chat completions",
    description="Generate chat completions using MedGemma. Compatible with OpenAI client libraries.",
)
async def chat_completions(
    request: ChatCompletionRequest,
    api_key: APIKeyDep,
    service: MedGemmaService = Depends(get_medgemma_service),
) -> ChatCompletionResponse:
    """
    Generate chat completion responses.

    Follows OpenAI API format for compatibility with existing tools and libraries.
    Supports multi-turn conversations with system prompts.

    Note: Streaming is not yet supported.
    """
    if not service.is_loaded:
        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail={"error": {"code": "model_not_loaded", "message": "Model is still loading. Please try again later."}},
        )

    if request.stream:
        raise HTTPException(
            status_code=status.HTTP_501_NOT_IMPLEMENTED,
            detail={"error": {"code": "streaming_not_supported", "message": "Streaming is not yet supported."}},
        )

    try:
        # Extract system prompt and conversation history
        system_prompt = None
        conversation_history = []
        user_prompt = ""

        for msg in request.messages:
            if msg.role == "system":
                system_prompt = msg.content
            elif msg.role == "user":
                # Last user message is the prompt
                user_prompt = msg.content
            else:
                conversation_history.append({"role": msg.role, "content": msg.content})

        # Generate response
        result = service.generate(
            prompt=user_prompt,
            system_prompt=system_prompt,
            conversation_history=conversation_history if conversation_history else None,
            max_new_tokens=request.max_tokens,
            temperature=request.temperature,
            top_p=request.top_p,
            top_k=request.top_k,
        )

        # Format as OpenAI response
        return ChatCompletionResponse(
            id=f"chatcmpl-{uuid.uuid4().hex[:8]}",
            model=result["model"],
            choices=[
                Choice(
                    index=0,
                    message={"role": "assistant", "content": result["response"]},
                    finish_reason="stop",
                )
            ],
            usage=UsageInfo(**result["usage"]),
        )

    except ValueError as e:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail={"error": {"code": "invalid_request", "message": str(e)}},
        )
    except Exception as e:
        logger.exception("Error in chat completion")
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail={"error": {"code": "internal_error", "message": str(e)}},
        )


# =============================================================================
# Medical Query Endpoint (Text-Only)
# =============================================================================


@app.post(
    "/v1/medical/query",
    response_model=MedicalQueryResponse,
    tags=["Medical"],
    summary="Text-only medical query",
    description="Submit medical questions or clinical cases for AI analysis. Optimized for long prompts (up to 10K tokens).",
)
async def medical_query(
    request: MedicalQueryRequest,
    api_key: APIKeyDep,
    service: MedGemmaService = Depends(get_medgemma_service),
) -> MedicalQueryResponse:
    """
    Process text-only medical queries.

    Ideal for:
    - Clinical case analysis
    - Differential diagnosis
    - Treatment recommendations
    - Medical literature questions
    - Patient history analysis

    Supports up to ~10,000 tokens in the query.
    """
    if not service.is_loaded:
        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail={"error": {"code": "model_not_loaded", "message": "Model is still loading."}},
        )

    try:
        # Convert conversation history if provided
        history = None
        if request.conversation_history:
            history = [
                {"role": msg.role, "content": msg.content}
                for msg in request.conversation_history
            ]

        # Generate response
        result = service.generate(
            prompt=request.query,
            system_prompt=request.system_prompt,
            conversation_history=history,
            max_new_tokens=request.max_tokens,
            temperature=request.temperature,
        )

        # Add disclaimer if requested
        disclaimer = MEDICAL_DISCLAIMER if request.include_disclaimer else None

        return MedicalQueryResponse(
            response=result["response"],
            usage=UsageInfo(**result["usage"]),
            model=result["model"],
            disclaimer=disclaimer,
        )

    except ValueError as e:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail={"error": {"code": "invalid_request", "message": str(e)}},
        )
    except Exception as e:
        logger.exception("Error in medical query")
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail={"error": {"code": "internal_error", "message": str(e)}},
        )


# =============================================================================
# Medical Image Analysis Endpoint
# =============================================================================


@app.post(
    "/v1/medical/analyze",
    response_model=ImageAnalysisResponse,
    tags=["Medical"],
    summary="Medical image analysis",
    description="Analyze medical images (X-rays, CT, MRI, pathology, dermatology) with AI.",
)
async def analyze_image(
    request: ImageAnalysisRequest,
    api_key: APIKeyDep,
    service: MedGemmaService = Depends(get_medgemma_service),
) -> ImageAnalysisResponse:
    """
    Analyze medical images with MedGemma.

    Supports multiple modalities:
    - Radiology: X-ray, CT, MRI
    - Pathology: Histopathology slides
    - Dermatology: Skin lesions, conditions
    - Ophthalmology: Retinal scans
    - Clinical photography

    Images should be base64-encoded or provided as data URLs.
    Maximum 4 images per request.
    """
    if not service.is_loaded:
        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail={"error": {"code": "model_not_loaded", "message": "Model is still loading."}},
        )

    try:
        # Build prompt with clinical context
        prompt_parts = []

        if request.image_modality:
            prompt_parts.append(f"[Image Type: {request.image_modality}]")

        if request.clinical_context:
            prompt_parts.append(f"[Clinical Context: {request.clinical_context}]")

        prompt_parts.append(request.query)

        if request.structured_output:
            prompt_parts.append(
                "\nPlease provide your analysis in a structured format with: "
                "1) Observations, 2) Findings, 3) Assessment, 4) Recommendations."
            )

        full_prompt = "\n\n".join(prompt_parts)

        # Generate response with images
        result = service.generate(
            prompt=full_prompt,
            system_prompt=request.system_prompt,
            images=request.images,
            max_new_tokens=request.max_tokens,
            temperature=request.temperature,
        )

        # Parse structured findings if requested
        findings = None
        if request.structured_output:
            # Simple parsing - extract numbered items
            lines = result["response"].split("\n")
            findings = [
                line.strip()
                for line in lines
                if line.strip() and (
                    line.strip()[0].isdigit()
                    or line.strip().startswith("-")
                    or line.strip().startswith("•")
                )
            ]

        return ImageAnalysisResponse(
            analysis=result["response"],
            findings=findings,
            usage=UsageInfo(**result["usage"]),
            model=result["model"],
            image_count=len(request.images),
        )

    except ValueError as e:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail={"error": {"code": "invalid_request", "message": str(e)}},
        )
    except Exception as e:
        logger.exception("Error in image analysis")
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail={"error": {"code": "internal_error", "message": str(e)}},
        )


# =============================================================================
# Medical Report Generation Endpoint
# =============================================================================


@app.post(
    "/v1/medical/report",
    response_model=MedicalReportResponse,
    tags=["Medical"],
    summary="Generate medical report",
    description="Generate structured medical reports from images (radiology, pathology, etc.).",
)
async def generate_report(
    request: MedicalReportRequest,
    api_key: APIKeyDep,
    service: MedGemmaService = Depends(get_medgemma_service),
) -> MedicalReportResponse:
    """
    Generate structured medical reports from images.

    Creates comprehensive reports following medical documentation standards.
    Includes:
    - Examination findings
    - Impressions
    - Recommendations
    - Differential diagnoses (when applicable)

    Supports radiology, pathology, dermatology, and ophthalmology reports.
    """
    if not service.is_loaded:
        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail={"error": {"code": "model_not_loaded", "message": "Model is still loading."}},
        )

    try:
        # Build report prompt based on report type
        report_prompts = {
            "radiology": """Generate a comprehensive radiology report for the provided image(s).
Include the following sections:
1. EXAMINATION: Type of imaging study
2. CLINICAL INDICATION: {indication}
3. COMPARISON: {comparison}
4. TECHNIQUE: Brief description if relevant
5. FINDINGS: Detailed systematic description of findings
6. IMPRESSION: Summary of key findings
7. RECOMMENDATIONS: Follow-up recommendations if any""",

            "pathology": """Generate a pathology report for the provided image(s).
Include the following sections:
1. SPECIMEN: Description of specimen
2. CLINICAL HISTORY: {indication}
3. GROSS DESCRIPTION: Macroscopic findings (if visible)
4. MICROSCOPIC DESCRIPTION: Detailed histological findings
5. DIAGNOSIS: Pathological diagnosis
6. COMMENTS: Additional relevant information
7. RECOMMENDATIONS: Further testing or follow-up if needed""",

            "dermatology": """Generate a dermatology assessment for the provided image(s).
Include the following sections:
1. CLINICAL PRESENTATION: Description of the lesion/condition
2. PATIENT HISTORY: {indication}
3. MORPHOLOGY: Shape, size, color, texture, borders
4. DISTRIBUTION: Location and pattern
5. DIFFERENTIAL DIAGNOSIS: List of possible diagnoses
6. ASSESSMENT: Most likely diagnosis with reasoning
7. RECOMMENDATIONS: Treatment options or further evaluation needed""",

            "ophthalmology": """Generate an ophthalmology report for the provided image(s).
Include the following sections:
1. EXAMINATION TYPE: Type of imaging (fundus, OCT, etc.)
2. CLINICAL INDICATION: {indication}
3. FINDINGS - RIGHT EYE (OD): Detailed findings
4. FINDINGS - LEFT EYE (OS): Detailed findings (if applicable)
5. ASSESSMENT: Interpretation of findings
6. RECOMMENDATIONS: Follow-up or treatment recommendations""",

            "general": """Generate a comprehensive medical image analysis report.
Include the following sections:
1. IMAGE TYPE: Description of the medical image
2. CLINICAL CONTEXT: {indication}
3. OBSERVATIONS: Systematic description of what is visible
4. FINDINGS: Key abnormalities or notable features
5. ASSESSMENT: Clinical interpretation
6. RECOMMENDATIONS: Suggested next steps or follow-up"""
        }

        # Get template and fill in details
        template = report_prompts.get(request.report_type, report_prompts["general"])
        prompt = template.format(
            indication=request.clinical_indication or "Not provided",
            comparison=request.comparison_studies or "None available",
        )

        # Add patient info if provided
        if request.patient_info:
            prompt = f"PATIENT INFORMATION: {request.patient_info}\n\n{prompt}"

        # Build specialized system prompt for report generation
        system_prompt = f"""You are an expert medical professional generating a formal {request.report_type} report.
Follow standard medical documentation practices. Be thorough, precise, and professional.
Always note limitations in image quality or visibility that may affect interpretation.
Include appropriate medical terminology while remaining clear."""

        # Generate report
        result = service.generate(
            prompt=prompt,
            system_prompt=system_prompt,
            images=request.images,
            max_new_tokens=request.max_tokens,
            temperature=0.3,  # Lower temperature for more consistent reports
        )

        # Try to parse sections from the report
        sections = {}
        current_section = None
        current_content = []

        for line in result["response"].split("\n"):
            line = line.strip()
            # Check for section headers (usually in caps or numbered)
            if line.endswith(":") and len(line) < 50:
                if current_section:
                    sections[current_section] = "\n".join(current_content).strip()
                current_section = line[:-1]
                current_content = []
            elif line.startswith(tuple("0123456789")) and "." in line[:3]:
                # Numbered section
                if current_section:
                    sections[current_section] = "\n".join(current_content).strip()
                parts = line.split(".", 1)
                if len(parts) > 1:
                    current_section = parts[1].strip().rstrip(":")
                    current_content = []
            else:
                current_content.append(line)

        if current_section:
            sections[current_section] = "\n".join(current_content).strip()

        return MedicalReportResponse(
            report=result["response"],
            report_type=request.report_type,
            sections=sections if sections else None,
            usage=UsageInfo(**result["usage"]),
            model=result["model"],
        )

    except ValueError as e:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail={"error": {"code": "invalid_request", "message": str(e)}},
        )
    except Exception as e:
        logger.exception("Error in report generation")
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail={"error": {"code": "internal_error", "message": str(e)}},
        )


# =============================================================================
# Error Handlers
# =============================================================================


@app.exception_handler(HTTPException)
async def http_exception_handler(request, exc: HTTPException):
    """Handle HTTP exceptions with consistent error format."""
    return JSONResponse(
        status_code=exc.status_code,
        content=exc.detail if isinstance(exc.detail, dict) else {"error": {"message": exc.detail}},
    )


@app.exception_handler(Exception)
async def general_exception_handler(request, exc: Exception):
    """Handle unexpected exceptions."""
    logger.exception("Unhandled exception")
    return JSONResponse(
        status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
        content={
            "error": {
                "code": "internal_error",
                "message": "An unexpected error occurred. Please try again later.",
                "type": "server_error",
            }
        },
    )


# =============================================================================
# Root Endpoint
# =============================================================================


@app.get("/", tags=["Root"])
async def root():
    """Root endpoint with API information."""
    return {
        "name": settings.api_title,
        "version": settings.api_version,
        "description": settings.api_description,
        "documentation": "/docs",
        "health": "/health",
        "endpoints": {
            "chat": "/v1/chat/completions",
            "medical_query": "/v1/medical/query",
            "image_analysis": "/v1/medical/analyze",
            "report_generation": "/v1/medical/report",
        },
    }


# =============================================================================
# Main Entry Point
# =============================================================================


if __name__ == "__main__":
    import uvicorn

    uvicorn.run(
        "src.main:app",
        host=settings.host,
        port=settings.port,
        workers=settings.workers,
        log_level=settings.log_level.lower(),
    )
